{% set name = "matrix_client" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0678af40f2cb2f0928a908a410c029747d40cb961ac5a3f1bd05aa35563c3156

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - urllib3

test:
  requires:
    - python {{ python_min }}
  imports:
    - matrix_client

about:
  home: https://github.com/matrix-org/matrix-python-sdk
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Matrix client-server SDK for Python 2 and 3.
  doc_url: https://matrix-org.github.io/matrix-python-sdk/
  dev_url: https://github.com/matrix-org/matrix-python-sdk

extra:
  recipe-maintainers:
    - setu4993
